# Generated by Django 5.1.7 on 2025-04-06 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category_delete_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Общее количество')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Продано')),
                ('damaged_quantity', models.PositiveIntegerField(default=0, verbose_name='Брак')),
                ('bonus_quantity', models.PositiveIntegerField(default=0, verbose_name='Бонус')),
                ('returned_quantity', models.PositiveIntegerField(default=0, verbose_name='Возвращено')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_instances', to='products.product')),
            ],
            options={
                'verbose_name': 'Товар партнера',
                'verbose_name_plural': 'Товары партнеров',
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'product')},
            },
        ),
    ]
