# Generated by Django 5.1.7 on 2025-04-30 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerinventory',
            options={'ordering': ['partner', 'product__name'], 'verbose_name': 'Инвентарь партнера', 'verbose_name_plural': 'Инвентарь партнеров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='partnerinventory',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='partnerinventory',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_inventories', to='products.product', verbose_name='Товар'),
        ),
    ]
