# Generated by Django 5.1.7 on 2025-03-20 08:19

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('self', 'Для себя'), ('store', 'Для магазина')], default='self', max_length=10, verbose_name='Тип заказа')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название магазина')),
                ('inn', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.orders.models.validate_inn], verbose_name='ИНН')),
                ('city', models.CharField(blank=True, choices=[('Ош', 'Ош'), ('Джалал-Абад', 'Джалал-Абад'), ('Баткен', 'Баткен')], max_length=50, null=True, verbose_name='Город')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию магазина',
                'verbose_name_plural': 'Заявки на регистрацию магазинов',
            },
        ),
    ]
