# Generated by Django 5.1.7 on 2025-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='is_bonus_marked',
            field=models.BooleanField(default=False, verbose_name='Отмечен как бонусный'),
        ),
    ]
