# Generated by Django 5.1.7 on 2025-04-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество бракованных товаров')),
                ('description', models.TextField(blank=True, verbose_name='Описание дефекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Бракованный товар',
                'verbose_name_plural': 'Бракованные товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
