# Generated by Django 5.1.7 on 2025-03-18 17:39

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='inn',
            field=models.CharField(max_length=14, unique=True, validators=[apps.orders.models.validate_inn], verbose_name='ИНН'),
        ),
    ]
