# Generated by Django 5.1.7 on 2025-04-16 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_defectitem'),
        ('products', '0002_product_image_delete_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='defectitem',
            index=models.Index(fields=['order'], name='orders_defe_order_i_a01f76_idx'),
        ),
        migrations.AddIndex(
            model_name='defectitem',
            index=models.Index(fields=['product'], name='orders_defe_product_cee596_idx'),
        ),
        migrations.AddIndex(
            model_name='defectitem',
            index=models.Index(fields=['created_at'], name='orders_defe_created_0f7dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['partner'], name='orders_orde_partner_285aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store'], name='orders_orde_store_i_6ed055_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['created_at'], name='orders_orde_created_861eeb_idx'),
        ),
    ]
