# Generated by Django 5.1.7 on 2025-04-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productrequest_is_bonus_marked'),
        ('products', '0004_remove_product_category_delete_category'),
        ('stores', '0004_storedebt_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='bonus_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='for_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='is_bonus_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('debt', 'В долг')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('received', 'Получен')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
