# Generated by Django 5.1.7 on 2025-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_defectitem_orders_defe_order_i_a01f76_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='defectitem',
            name='orders_defe_order_i_a01f76_idx',
        ),
        migrations.RemoveIndex(
            model_name='defectitem',
            name='orders_defe_product_cee596_idx',
        ),
        migrations.RemoveIndex(
            model_name='defectitem',
            name='orders_defe_created_0f7dcb_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_t_d697ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_partner_285aa9_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_store_i_6ed055_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5d347b_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_product_32ff41_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_created_861eeb_idx',
        ),
    ]
