# Generated by Django 5.1.7 on 2025-04-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_productrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос на товар', 'verbose_name_plural': 'Запросы на товары'},
        ),
    ]
