# Generated by Django 5.1.7 on 2025-05-03 19:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_defectitem_orders_defe_order_i_a01f76_idx_and_more'),
        ('products', '0006_alter_partnerinventory_options_alter_product_options_and_more'),
        ('stores', '0006_remove_store_expenses_alter_store_partner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('admin_to_partner', 'Админ → Партнер'), ('partner_to_store', 'Партнер → Магазин')], db_index=True, max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_received', to=settings.AUTH_USER_MODEL, verbose_name='Партнер (получатель)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_process', 'В обработке'), ('confirmed', 'Подтвержден'), ('rejected', 'Отклонен')], db_index=True, default='in_process', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.store', verbose_name='Магазин (получатель)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за единицу (на момент заказа)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Товар (на момент заказа)'),
        ),
    ]
