# Generated by Django 5.1.7 on 2025-04-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productrequest_options'),
        ('products', '0005_product_is_active_partnerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='for_store',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='partner_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_requests', to='products.partnerproduct'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='request_type',
            field=models.CharField(choices=[('SELF', 'Для себя'), ('STORE', 'Для магазина')], default='SELF', max_length=5),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='payment_method',
            field=models.CharField(choices=[('debt', 'В долг')], default='debt', max_length=10),
        ),
    ]
