# Generated by Django 5.1.7 on 2025-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_productrequest_for_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Уникальный идентификатор для связывания запросов в группу', null=True, verbose_name='ID групповой заявки'),
        ),
    ]
