--
-- PostgreSQL database dump
--

-- Dumped from database version 13.20
-- Dumped by pg_dump version 13.20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: stores_city; Type: TABLE; Schema: public; Owner: baza_user
--

CREATE TABLE public.stores_city (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.stores_city OWNER TO baza_user;

--
-- Name: stores_city_id_seq; Type: SEQUENCE; Schema: public; Owner: baza_user
--

ALTER TABLE public.stores_city ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: stores_city; Type: TABLE DATA; Schema: public; Owner: baza_user
--

COPY public.stores_city (id, name) FROM stdin;
1	Чоң алай
2	Карамык
3	Жар башы
4	Сарыгмоол
5	Кашка суу
6	Ачы суу
7	Шибе
8	Дарооткоргон
9	Талдык
10	Кабык
12	Черемушка
11	Сары Таш
13	Смуту
14	Эркештам
15	Ишкаван
16	Жекенди
17	Гулбар
18	Кара теит
19	Араван
20	Жалал Абад
21	Кызыл байрак
22	Базар коргон
23	Ошский район
24	Көк жаңгак
25	Зайнабидинова
26	Сму
27	Араванский
28	Барпы
29	Фрунзенский
30	Сузак
31	Толойкон
32	Южный
33	Баргы
34	Учар
35	Жапалак
36	Көгарт
37	Западный
38	Хбк
39	Ноокет
40	Келечек
41	Юго восток
42	Кочкар ата
43	Ош шаары
44	Шамалды сай
45	Куршаб
46	Арстанбап
47	Майлу суу
48	Кызыл сеңир
49	Правда
50	Ташкөмүр
51	Жаңы арык
52	Кызыл жар
53	Ынтымак
54	Садырбай
55	Кербен
56	Аксы
57	Отуз адыр
58	Ала Бука
59	Каарман
60	Кадамжай
61	Кыргыз чек
62	Айдаркен
63	Учкун
64	Круг байрак
65	10 адыр
66	Арка
67	Жеңиш айылы
68	Прогерсс
69	Торговый
70	Красный маяк
71	Баткен
72	Октярбский
73	Лейлек
74	Кара дыйкан
75	Исфана
76	Жылалды
77	Савет
78	Сүлүктү
79	Кара кулжа
80	Ноокат
81	Мырзаке
82	Кыргыз Ата
83	Өзгөн
84	Заргер
85	Атамерек
86	Кызыл кыя
87	Кашкалдак
88	Өрнөк
89	Карван
90	Жал
91	Жаны базар
92	Көк жар
93	Ноокат базр
94	Жаны ноокат
\.


--
-- Name: stores_city_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baza_user
--

SELECT pg_catalog.setval('public.stores_city_id_seq', 95, true);


--
-- Name: stores_city stores_city_name_key; Type: CONSTRAINT; Schema: public; Owner: baza_user
--

ALTER TABLE ONLY public.stores_city
    ADD CONSTRAINT stores_city_name_key UNIQUE (name);


--
-- Name: stores_city stores_city_pkey; Type: CONSTRAINT; Schema: public; Owner: baza_user
--

ALTER TABLE ONLY public.stores_city
    ADD CONSTRAINT stores_city_pkey PRIMARY KEY (id);


--
-- Name: stores_city_name_a8381841_like; Type: INDEX; Schema: public; Owner: baza_user
--

CREATE INDEX stores_city_name_a8381841_like ON public.stores_city USING btree (name varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

