version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./media:/app/media        # ← фикс: монтируем локальную папку
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  celery:
    build: .
    command: [ "celery", "-A", "backend", "worker", "--loglevel=info" ]
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
      - ./media:/app/media        # ← тоже фикс: монтируем локальную папку
      - logs_volume:/app/logs
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

volumes:
  postgres_data:
  redis_data:
  static_volume:
  logs_volume:
