# Generated by Django 5.1.7 on 2025-04-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0005_remove_productrequest_for_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='orders.productrequest'),
        ),
    ]
