# Generated by Django 5.1.7 on 2025-04-11 15:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_remove_storedebt_paid_at_storedebt_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt', 'Долг'), ('payment', 'Оплата'), ('bonus', 'Бонус'), ('defect', 'Брак')], max_length=20, verbose_name='Тип записи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип записи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_finance_entries', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ручная финансовая запись',
                'verbose_name_plural': 'Ручные финансовые записи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общие продажи')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общие расходы')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая прибыль')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий долг')),
                ('total_paid_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплаченный долг')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма бонусов')),
                ('total_defect', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма брака')),
                ('items_sold', models.PositiveIntegerField(default=0, verbose_name='Количество проданных товаров')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ежедневная статистика',
                'verbose_name_plural': 'Ежедневная статистика',
                'ordering': ['-date'],
                'unique_together': {('user', 'store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общие продажи')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общие расходы')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая прибыль')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий долг')),
                ('total_paid_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплаченный долг')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма бонусов')),
                ('total_defect', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма брака')),
                ('items_sold', models.PositiveIntegerField(default=0, verbose_name='Количество проданных товаров')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statistics', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Месячная статистика',
                'verbose_name_plural': 'Месячная статистика',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'store', 'year', 'month')},
            },
        ),
    ]
