# Generated by Django 5.1.7 on 2025-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Доход')),
                ('expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Расход')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Остаток')),
                ('bonus', models.IntegerField(default=0, verbose_name='Бонусные товары')),
                ('defect', models.IntegerField(default=0, verbose_name='Бракованные товары')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Долг')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Погашение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
            ],
            options={
                'verbose_name': 'Финансы',
                'verbose_name_plural': 'Финансы',
            },
        ),
    ]
