# Generated by Django 5.1.7 on 2025-04-12 01:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('stores', '0002_remove_storedebt_paid_at_storedebt_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt', 'Долг'), ('debt_payment', 'Оплата долга'), ('bonus', 'Бонус'), ('defect', 'Брак')], max_length=20, verbose_name='Тип записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Финансовая запись партнера',
                'verbose_name_plural': 'Финансовые записи партнеров',
            },
        ),
        migrations.CreateModel(
            name='ProductDailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('requested_quantity', models.PositiveIntegerField(default=0, verbose_name='Запрошенное количество')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Проданное количество')),
                ('bonus_quantity', models.PositiveIntegerField(default=0, verbose_name='Бонусное количество')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Бракованное количество')),
                ('remaining_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма дохода')),
            ],
            options={
                'verbose_name': 'Статистика товара',
                'verbose_name_plural': 'Статистика товаров',
            },
        ),
        migrations.CreateModel(
            name='StoreFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt', 'Долг'), ('debt_payment', 'Оплата долга'), ('bonus', 'Бонус'), ('defect', 'Брак')], max_length=20, verbose_name='Тип записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Финансовая запись магазина',
                'verbose_name_plural': 'Финансовые записи магазинов',
            },
        ),
        migrations.RemoveField(
            model_name='financeentry',
            name='store',
        ),
        migrations.RemoveField(
            model_name='financeentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manualfinanceentry',
            name='store',
        ),
        migrations.RemoveField(
            model_name='manualfinanceentry',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='monthlystatistics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlystatistics',
            name='store',
        ),
        migrations.RemoveField(
            model_name='monthlystatistics',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='dailystatistics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий баланс'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма бонусов'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_bonus_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бонусных товаров'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_debt_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Погашенные долги'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_defect_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бракованных товаров'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общие расходы'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий доход'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='total_remaining_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток товаров'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='dailystatistics',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий долг'),
        ),
        migrations.AddConstraint(
            model_name='dailystatistics',
            constraint=models.UniqueConstraint(fields=('date', 'partner', 'store'), name='unique_daily_statistics'),
        ),
        migrations.AddField(
            model_name='partnerfinanceentry',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='productdailystatistics',
            name='statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stats', to='finance.dailystatistics', verbose_name='Основная статистика'),
        ),
        migrations.AddField(
            model_name='storefinanceentry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.DeleteModel(
            name='FinanceEntry',
        ),
        migrations.DeleteModel(
            name='ManualFinanceEntry',
        ),
        migrations.DeleteModel(
            name='MonthlyStatistics',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='data_json',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='items_sold',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='total_bonus',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='total_defect',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='total_paid_debt',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='productdailystatistics',
            constraint=models.UniqueConstraint(fields=('statistics', 'product_id'), name='unique_product_daily_statistics'),
        ),
    ]
