# Generated by Django 5.1.7 on 2025-03-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeentry_partnerfinancestat_storefinancestat_and_more'),
        ('stores', '0003_remove_storedebt_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Архивная сводка',
                'verbose_name_plural': 'Архивные сводки',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CalendarStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('has_sales', models.BooleanField(default=False, verbose_name='Были продажи')),
                ('has_requests', models.BooleanField(default=False, verbose_name='Были запросы')),
                ('has_expenses', models.BooleanField(default=False, verbose_name='Были расходы')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_marks', to='stores.city', verbose_name='Город')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_marks', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_marks', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Метка календаря',
                'verbose_name_plural': 'Метки календаря',
                'ordering': ['-date'],
                'unique_together': {('date', 'user', 'store', 'city')},
            },
        ),
    ]
