# Generated by Django 5.1.7 on 2025-03-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('stores', '0002_alter_store_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='balance',
        ),
        migrations.AlterField(
            model_name='finance',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Бонусные товары'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='defect',
            field=models.IntegerField(default=0, verbose_name='Бракованные товары'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
    ]
