# Generated by Django 5.1.7 on 2025-04-12 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_partnerfinanceentry_productdailystatistics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Всего заказов')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего продаж')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего расходов')),
                ('total_defects', models.IntegerField(default=0, verbose_name='Всего бракованных товаров')),
                ('total_bonuses', models.IntegerField(default=0, verbose_name='Всего бонусных товаров')),
                ('data_json', models.JSONField(default=dict, verbose_name='Дополнительные данные (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Финансовая статистика',
                'verbose_name_plural': 'Финансовая статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ManualFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('other', 'Другое')], default='expense', max_length=10, verbose_name='Тип записи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
