# Generated by Django 5.1.7 on 2025-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_finance_balance_alter_finance_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Остаток'),
        ),
    ]
