# Generated by Django 5.1.7 on 2025-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_archiveddailysummary_calendarstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeentry',
            options={'ordering': ['-date'], 'verbose_name': 'Финансовая запись', 'verbose_name_plural': 'Финансовые записи'},
        ),
        migrations.AlterModelOptions(
            name='partnerfinancestat',
            options={'ordering': ['-date'], 'verbose_name': 'Финансовая статистика партнера', 'verbose_name_plural': 'Финансовая статистика партнеров'},
        ),
        migrations.AlterModelOptions(
            name='storefinancestat',
            options={'ordering': ['-date'], 'verbose_name': 'Финансовая статистика магазина', 'verbose_name_plural': 'Финансовая статистика магазинов'},
        ),
        migrations.AddField(
            model_name='calendarstatistics',
            name='has_debt_payment',
            field=models.BooleanField(default=False, verbose_name='Были погашения долгов'),
        ),
    ]
