# Generated by Django 5.1.7 on 2025-04-16 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financestatistics_manualfinanceentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailystatistics',
            index=models.Index(fields=['date'], name='finance_dai_date_07bb88_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystatistics',
            index=models.Index(fields=['partner'], name='finance_dai_partner_c8905a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystatistics',
            index=models.Index(fields=['store'], name='finance_dai_store_i_fc7c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='financestatistics',
            index=models.Index(fields=['date'], name='finance_fin_date_368a86_idx'),
        ),
        migrations.AddIndex(
            model_name='manualfinanceentry',
            index=models.Index(fields=['user', 'date'], name='finance_man_user_id_8acedf_idx'),
        ),
        migrations.AddIndex(
            model_name='manualfinanceentry',
            index=models.Index(fields=['entry_type'], name='finance_man_entry_t_200dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerfinanceentry',
            index=models.Index(fields=['partner', 'date'], name='finance_par_partner_f89e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerfinanceentry',
            index=models.Index(fields=['entry_type'], name='finance_par_entry_t_65cae8_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerfinanceentry',
            index=models.Index(fields=['created_at'], name='finance_par_created_da49c8_idx'),
        ),
        migrations.AddIndex(
            model_name='productdailystatistics',
            index=models.Index(fields=['statistics'], name='finance_pro_statist_c108bf_idx'),
        ),
        migrations.AddIndex(
            model_name='productdailystatistics',
            index=models.Index(fields=['product_id'], name='finance_pro_product_589c89_idx'),
        ),
        migrations.AddIndex(
            model_name='storefinanceentry',
            index=models.Index(fields=['store', 'date'], name='finance_sto_store_i_a8d5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='storefinanceentry',
            index=models.Index(fields=['entry_type'], name='finance_sto_entry_t_05c4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='storefinanceentry',
            index=models.Index(fields=['created_at'], name='finance_sto_created_aa24fd_idx'),
        ),
    ]
