# Generated by Django 5.1.7 on 2025-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_dailystatistics_finance_dai_date_07bb88_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfinanceentry',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='storefinanceentry',
            name='store',
        ),
        migrations.RemoveIndex(
            model_name='dailystatistics',
            name='finance_dai_date_07bb88_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailystatistics',
            name='finance_dai_partner_c8905a_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailystatistics',
            name='finance_dai_store_i_fc7c1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='financestatistics',
            name='finance_fin_date_368a86_idx',
        ),
        migrations.RemoveIndex(
            model_name='manualfinanceentry',
            name='finance_man_user_id_8acedf_idx',
        ),
        migrations.RemoveIndex(
            model_name='manualfinanceentry',
            name='finance_man_entry_t_200dbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='productdailystatistics',
            name='finance_pro_statist_c108bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='productdailystatistics',
            name='finance_pro_product_589c89_idx',
        ),
        migrations.DeleteModel(
            name='PartnerFinanceEntry',
        ),
        migrations.DeleteModel(
            name='StoreFinanceEntry',
        ),
    ]
