# Generated by Django 5.1.7 on 2025-04-06 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financeentry_options_and_more'),
        ('products', '0005_product_is_active_partnerproduct'),
        ('stores', '0005_store_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeentry',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='financeentry',
            name='income',
        ),
        migrations.RemoveField(
            model_name='financeentry',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='partnerfinancestat',
            name='total_approved_cash',
        ),
        migrations.AddField(
            model_name='archiveddailysummary',
            name='total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма бонусов'),
        ),
        migrations.AddField(
            model_name='archiveddailysummary',
            name='total_damages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма брака'),
        ),
        migrations.AddField(
            model_name='archiveddailysummary',
            name='total_returns',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма возвратов'),
        ),
        migrations.AddField(
            model_name='calendarstatistics',
            name='has_damages',
            field=models.BooleanField(default=False, verbose_name='Был брак'),
        ),
        migrations.AddField(
            model_name='calendarstatistics',
            name='has_returns',
            field=models.BooleanField(default=False, verbose_name='Были возвраты'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='entry_type',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход'), ('sale', 'Продажа'), ('damage', 'Брак'), ('return', 'Возврат')], default='expense', max_length=10, verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='partner_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='products.partnerproduct', verbose_name='Товар из каталога'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_approved_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Долг (отложенный доход)'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_bonus_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость бонусов'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расходы'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Продано'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_sold_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданного'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонусы'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='archiveddailysummary',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='archiveddailysummary',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма расходов'),
        ),
        migrations.AlterField(
            model_name='archiveddailysummary',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая прибыль'),
        ),
        migrations.AlterField(
            model_name='archiveddailysummary',
            name='total_requests',
            field=models.IntegerField(default=0, verbose_name='Всего запросов'),
        ),
        migrations.AlterField(
            model_name='archiveddailysummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма продаж'),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='partnerfinancestat',
            name='total_damaged_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Убытки от брака'),
        ),
        migrations.AlterField(
            model_name='partnerfinancestat',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='storefinancestat',
            name='total_approved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма поставок'),
        ),
        migrations.AlterField(
            model_name='storefinancestat',
            name='total_damaged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Брак'),
        ),
        migrations.AlterField(
            model_name='storefinancestat',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Долг'),
        ),
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Общее количество')),
                ('total_sold', models.PositiveIntegerField(default=0, verbose_name='Продано')),
                ('total_damaged', models.PositiveIntegerField(default=0, verbose_name='Брак')),
                ('total_bonus', models.PositiveIntegerField(default=0, verbose_name='Бонус')),
                ('total_returned', models.PositiveIntegerField(default=0, verbose_name='Возвращено')),
                ('total_remaining', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('total_sold_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость проданного')),
                ('total_damaged_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость брака')),
                ('total_bonus_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость бонусов')),
                ('total_remaining_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость остатков')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Детализация по товарам')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сводка по остаткам',
                'verbose_name_plural': 'Сводки по остаткам',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
