# Generated by Django 5.1.7 on 2025-04-16 16:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_partnerfinanceentry_partner_and_more'),
        ('stores', '0002_remove_storedebt_paid_at_storedebt_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt', 'Долг'), ('debt_payment', 'Оплата долга'), ('bonus', 'Бонус'), ('defect', 'Брак')], max_length=20, verbose_name='Тип записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Финансовая запись партнера',
                'verbose_name_plural': 'Финансовые записи партнеров',
            },
        ),
        migrations.CreateModel(
            name='StoreFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt', 'Долг'), ('debt_payment', 'Оплата долга'), ('bonus', 'Бонус'), ('defect', 'Брак')], max_length=20, verbose_name='Тип записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Финансовая запись магазина',
                'verbose_name_plural': 'Финансовые записи магазинов',
            },
        ),
    ]
