# Generated by Django 5.1.7 on 2025-04-07 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_financeentry_expense_and_more'),
        ('stores', '0005_store_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfinancestat',
            name='total_approved_debt',
        ),
        migrations.RemoveField(
            model_name='partnerfinancestat',
            name='total_bonus_value',
        ),
        migrations.RemoveField(
            model_name='partnerfinancestat',
            name='total_damaged_loss',
        ),
        migrations.RemoveField(
            model_name='partnerfinancestat',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='partnerfinancestat',
            name='total_sold',
        ),
        migrations.RemoveField(
            model_name='storefinancestat',
            name='total_approved',
        ),
        migrations.RemoveField(
            model_name='storefinancestat',
            name='total_bonus',
        ),
        migrations.RemoveField(
            model_name='storefinancestat',
            name='total_damaged',
        ),
        migrations.RemoveField(
            model_name='storefinancestat',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='financeentry',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='detailed_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детальные данные по товарам'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_bonus_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество бонусных товаров'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_damaged_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество бракованных товаров'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_debt_to_admin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Долг администратору'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_remaining_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий остаток товаров'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма запрошенных товаров'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_requested_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество запрошенных товаров'),
        ),
        migrations.AddField(
            model_name='partnerfinancestat',
            name='total_sold_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма проданных товаров'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='detailed_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детальные данные по товарам'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_bonus_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество бонусных товаров'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_damaged_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество бракованных товаров'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_paid_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Погашенный долг'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_partner_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расходы партнера'),
        ),
        migrations.AddField(
            model_name='storefinancestat',
            name='total_received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество полученных товаров'),
        ),
        migrations.AlterField(
            model_name='partnerfinancestat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='partnerfinancestat',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общие расходы'),
        ),
        migrations.AlterField(
            model_name='partnerfinancestat',
            name='total_sold_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество проданных товаров'),
        ),
        migrations.AlterField(
            model_name='storefinancestat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='storefinancestat',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий долг'),
        ),
    ]
