# Generated by Django 5.1.7 on 2025-04-28 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_partnerfinanceentry_storefinanceentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма расхода')),
                ('description', models.TextField(help_text='Обязательное поле. Укажите, на что были потрачены средства.', verbose_name='Описание расхода')),
                ('expense_date', models.DateField(verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Расход партнера',
                'verbose_name_plural': 'Расходы партнеров',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['partner', 'expense_date'], name='finance_par_partner_08ecaa_idx')],
            },
        ),
    ]
