# Generated by Django 5.1.7 on 2025-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_partnerfinancestat_total_approved_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefinancestat',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль'),
        ),
    ]
