# Generated by Django 5.1.7 on 2025-04-11 04:18

import apps.chats.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.chats.models.chat_file_upload_path)),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ')], default='text', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['admin'], name='chats_chat_admin_i_2f3872_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['partner'], name='chats_chat_partner_36faab_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['updated_at'], name='chats_chat_updated_b952c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('admin', 'partner')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='chats_messa_chat_id_014e32_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'is_read'], name='chats_messa_sender__678e0f_idx'),
        ),
    ]
