# Generated by Django 5.1.7 on 2025-03-16 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('login', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Логин')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Телефон')),
                ('full_name', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(15, message='Имя должно быть не менее 15 символов'), django.core.validators.MaxLengthValidator(24, message='Имя должно быть не более 24 символов')], verbose_name='ФИО')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('partner', 'Партнер')], default='partner', max_length=10, verbose_name='Роль')),
                ('token_reset', models.CharField(blank=True, max_length=5, null=True, verbose_name='Токен сброса пароля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
