# Generated by Django 5.1.7 on 2025-03-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
