# Generated by Django 5.1.7 on 2025-03-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reset_verified',
        ),
    ]
