# Generated by Django 5.1.7 on 2025-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_reset_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/photos/default.jpg', null=True, upload_to='users/photos/', verbose_name='Фото профиля'),
        ),
    ]
