# Generated by Django 5.1.7 on 2025-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=14, unique=True)),
                ('city', models.CharField(choices=[('Ош', 'Ош'), ('Джалал-Абад', 'Джалал-Абад'), ('Баткен', 'Баткен')], max_length=50)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
