# Generated by Django 5.1.7 on 2025-04-11 09:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedebt',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='storedebt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='StoreDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма оплаты')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий к оплате')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Оплата долга',
                'verbose_name_plural': 'Оплаты долгов',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма расхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание расхода')),
                ('expense_date', models.DateField(verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Расход магазина',
                'verbose_name_plural': 'Расходы магазинов',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StoreDefect',
        ),
    ]
