# Generated by Django 5.1.7 on 2025-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='inn',
            field=models.CharField(max_length=14, unique=True, verbose_name='ИНН'),
        ),
    ]
