# Generated by Django 5.1.7 on 2025-03-22 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('inn', models.CharField(max_length=14, unique=True, verbose_name='ИНН магазина')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название магазина')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Активирована'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.RemoveField(
            model_name='store',
            name='order',
        ),
        migrations.RemoveField(
            model_name='store',
            name='payment',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='contact_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='debt_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Лимит долга'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма оплат'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='store',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Текущий долг'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='inactive', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
