# Generated by Django 5.1.7 on 2025-03-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productrequest_is_bonus_marked'),
        ('stores', '0002_city_alter_store_options_remove_store_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedebt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storedebt',
            name='description',
        ),
        migrations.AddField(
            model_name='storedebt',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='orders.productrequest'),
        ),
        migrations.AlterField(
            model_name='storedebt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='storedebt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storedebt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storedebt',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedebt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='stores.store'),
        ),
    ]
