# Generated by Django 5.1.7 on 2025-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='approved', max_length=10, verbose_name='Статус'),
        ),
    ]
