# Generated by Django 5.1.7 on 2025-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
