# Generated by Django 5.1.7 on 2025-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedebt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Погашенная сумма'),
        ),
    ]
