# Generated by Django 5.1.7 on 2025-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_store_expenses_alter_store_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='inn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название магазина'),
        ),
    ]
