# Generated by Django 5.1.7 on 2025-04-12 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_status', 'Статус заказа'), ('store_approval', 'Одобрение магазина'), ('registration', 'Регистрация'), ('message', 'Сообщение'), ('financial', 'Финансовое уведомление'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_notifications', models.BooleanField(default=True, verbose_name='Уведомления о статусе заказа')),
                ('store_approval_notifications', models.BooleanField(default=True, verbose_name='Уведомления об одобрении магазина')),
                ('registration_notifications', models.BooleanField(default=True, verbose_name='Уведомления о регистрации')),
                ('message_notifications', models.BooleanField(default=True, verbose_name='Уведомления о сообщениях')),
                ('financial_notifications', models.BooleanField(default=True, verbose_name='Финансовые уведомления')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
