# Generated by Django 5.1.7 on 2025-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Контекстные данные'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип уведомления'),
        ),
    ]
